### ISSUE TITLE
Support for nestjs applications

### ISSUE THREAD

**Issue by fatemeh76m** [memlucky71/rest-bdd-testing#2]
**Is your feature request related to a problem? Please describe.**
Invoking rest-bdd-testing module with nestjs app causes problem. It seems that this module only supports nodejs and express applications.

**Describe the solution you'd like**
Only a slight change on the request options (hostname and port) for sending request to the application in this module can provide the support for nestjs.

**Additional context**
Since typescript and nestjs use is growing rapidly, it will be a great job to add the support for nestjs applications.

**Comment by memlucky71** [comment]
@fatemeh76m Thank you very much. Make free with making a PR.
